### ISSUE TITLE
[Reward included] Implement 24 bit MSB padding conversion in coreaudio

### ISSUE THREAD

**Issue by macdavis** [wm4/mpv_backup#2]
Not sure if this is appropriate place to contact you. Anyway, as you may know, mpv's CoreAudio-Exclusive AO is buggy when playing 24-Bit music. I managed to fixed the major problem, but I don't know how to achieve "32->24 bit conversion, with MSB padding", which was added by you in [commit 90dd2](https://github.com/mpv-player/mpv/commit/90dd2298713d3414bad39b6e8648490cd9f52603#diff-a5ca0b5894324f8bb54bb9fffad29d1e).

If you are interested, please don't hesitate to contact me via mpv_coreaudio@protonmail.com, or leave a message here. I am more than happy to discuss both compensation and solution to this issue with you.

**Comment by wm4** [comment]
No I don't know that it's broken. Normally, coreaudio takes floats only, which should be just enough to pass through 24 bit losslessly. You must be talking about integer formats, for which Apple dropped support a while ago (but maybe they undropped it). You could just reject these formats or somehow force floating point mode.

Yes, I removed 24 bit formats. FFmpeg doesn't support 24 bit audio. It always converts it to 32 bit, and makes the lowest 8 bits padding. This can be convert back to 24 bit without loss. Some audio APIs sometimes want the data in a different form, even if the number of bits is the same. 32 bit with MSB padding would mean that the padding bits are the high bits (instead of the low bits like in FFmpeg). The helper which I added in the commit you pointed out does these conversion (but only through the helpers, not the normal API). ao_wasapi uses the helper, and thus probably supports the format you mentioned.

All you need to do is to make use of the helper, and adjust the format negotiation code. The latter is probably the hardest part because it's a mess. I once tried to clean this up by mapping everything to mpv internal formats, which will make 24 bit support harder. Though if it mistakenly accepts 32-bit-with.-MSB-padding as normal 32 bit formats, it should be trivial to fix this by rejecting this format.

I wouldn't mind doing some development with some compensation, but there are the following things that speak against it:
- I probably don't have any audio equipment to test that would likely trigger your case
- I'm stuck on an old OSX version and can't update (because Apple hates its users)
- Filing taxes for this is surprisingly (or unsurprisingly) horrible where I live (basically I'd need to create a company)
- I certainly don't enjoy hacking on code that interacts with OSX APIs, and most likely you'd have to fight driver bugs/idiosyncrasies

**Comment by macdavis** [comment]
Thanks for your detailed explanation, and yes, I am talking about the integer format.

Maybe I underestimate the actual work, but I can't see why format negotiation is a mess for CoreAudio. To me, it's pretty straightforward, as CoreAudio tells you exactly what 32/24 Bit format is needed. All we need is doing the conversion accordingly. The hardware format can be retrieved via `kAudioStreamPropertyAvailablePhysicalFormats`, where some important parameters are,
- `mBitsPerChannel` can be played around to tell you the highest bit depth (24/32) supported.
- `mBytesPerPacket` tells you whether is s24 (6) or "s24 in s32" (8).
- `asbd->mFormatFlags = kAudioFormatFlagIsAlignedHigh` tells you whether is LSB padding (This flag exists) or MSB padding (This flag doesn't exist).

So, the idea is,

> 1. make a for loop to check `kAudioStreamPropertyAvailablePhysicalFormats`.
> 2. if `highest_mBitsPerChannel = 32, don't do conversion.` //This is a 32 Bit device.
> 3. if `(highest_mBitsPerChannel = 24) & (mBytesPerPacket = 8) & (asbd->mFormatFlags = kAudioFormatFlagIsAlignedHigh), don't do conversion.` //This is a 24 Bit device with LSB padding in 32 Bit, same as mpv's s32 format.
> 4. if `(highest_mBitsPerChannel = 24) & (mBytesPerPacket = 8) & (NO kAudioFormatFlagIsAlignedHigh flag), do MSB conversion.` //This is a 24 Bit device with MSB padding in 32 Bit.
> 5. if `(highest_mBitsPerChannel = 24) & (mBytesPerPacket = 6) & (asbd->mFormatFlags =kAudioFormatFlagIsPacked), do s24 conversion.` //This is a packed s24 device.

Up to now, I managed to set "if case 4 happens, set to standard float mode". The problem is not knowing how to insert the MSB conversion conversion and connect to AO.

For your concerns,

1. I can send a DAC to you if that would help. Or, you can simply send whatever code you modified and let me do the test. I don't mind repeated tests.
 
2. I'm not sure what OS version you're on. If it is above OS X 10.9 Mavericks, then it's fine. If not, similarly, I can send you a hard drive with the latest OS so that you don't need to worry about messing your own system.

3. This one I don't know. What about donation?

4.  I understand you once had nightmares dealing with CoreAudio, but if my idea is correct, most of the work is about connecting conversion to AO. And what I care the most is doing MSB conversion. s24 conversion is optional as my device is not the case anyway.

**Comment by wm4** [comment]
Like I said, basically you need to change from `ao_read_data` to `ao_read_data_converted`.

**Comment by macdavis** [comment]
Thanks for your hint!
